name: GHAction zadanie2

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  ci_step:
    name: Build, tag and push Docker image
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_REPO: 99534/sprawozdaniazdockera
      GHCR_REPO: ghcr.io/99534/sprawozdaniazdockera
      BUILD_CACHE: 99534/sprawozdaniazdockera:cache

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v4

      - name: Docker metadata definitions
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          flavor: latest=false
          tags: |
            type=sha,priority=100,prefix=sha-,format=short
            type=semver,priority=200,pattern={{version}}

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v3

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build amd64 image for CVE scan
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          cache-from: type=registry,ref=${{ env.BUILD_CACHE }}
          cache-to: type=registry,ref=${{ env.BUILD_CACHE }},mode=max
          tags: ${{ env.GHCR_REPO }}:sha-${{ github.sha }}-scan-amd64

      - name: Scan built amd64 image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.GHCR_REPO }}:sha-${{ github.sha }}-scan-amd64
          severity: CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Build and push Docker image (multi-arch)
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=${{ env.BUILD_CACHE }}
          cache-to: type=registry,ref=${{ env.BUILD_CACHE }},mode=max
          tags: |
            ${{ env.DOCKERHUB_REPO }}:v1.0
            ${{ env.GHCR_REPO }}:v1.0
